/**
 * ANEXO I DA NR-04 — Relação CNAE (versão 2.0) × Grau de Risco.
 *
 * FONTE: texto oficial da NR-04, redação dada pela Portaria MTP nº 2.318, de
 * 03/08/2022, com a alteração da Portaria MTP nº 4.219, de 20/12/2022.
 * Transcrito integralmente do Anexo I publicado pelo Ministério do Trabalho.
 *
 * ---------------------------------------------------------------------------
 * POR QUE A CHAVE TEM 5 DÍGITOS
 * ---------------------------------------------------------------------------
 * O Anexo I classifica na CLASSE do CNAE (5 dígitos — ex.: 86.50-0), não na
 * subclasse de 7 dígitos que aparece no cartão CNPJ (ex.: 86.50-0-04). Toda
 * subclasse herda o grau da sua classe. Por isso a consulta normaliza o código
 * recebido para os 5 primeiros dígitos antes de procurar aqui.
 *
 * Esta tabela é a ÚNICA fonte de grau de risco do sistema. Ela não estima,
 * não interpola por divisão e não assume padrão: CNAE fora desta relação
 * retorna "não classificado", para que a decisão seja de um profissional
 * habilitado e não de um palpite do software.
 *
 * O grau de risco define o dimensionamento do SESMT (Anexo II) e entra em
 * documentos com valor legal. Um dígito errado aqui vira laudo errado.
 */

export type GrauDeRisco = 1 | 2 | 3 | 4;

export interface ClasseCnae {
  /** Denominação oficial, exatamente como consta no Anexo I. */
  denominacao: string;
  grau: GrauDeRisco;
}

/** Chave: classe CNAE com 5 dígitos, sem pontuação (ex.: '86500' = 86.50-0). */
export const NR4_ANEXO_I: Record<string, ClasseCnae> = {
  // ===== A — AGRICULTURA, PECUÁRIA, PRODUÇÃO FLORESTAL, PESCA E AQUICULTURA =====
  '01113': { denominacao: 'Cultivo de cereais', grau: 3 },
  '01121': { denominacao: 'Cultivo de algodão herbáceo e de outras fibras de lavoura temporária', grau: 3 },
  '01130': { denominacao: 'Cultivo de cana-de-açúcar', grau: 3 },
  '01148': { denominacao: 'Cultivo de fumo', grau: 3 },
  '01156': { denominacao: 'Cultivo de soja', grau: 3 },
  '01164': { denominacao: 'Cultivo de oleaginosas de lavoura temporária, exceto soja', grau: 3 },
  '01199': { denominacao: 'Cultivo de plantas de lavoura temporária não especificadas anteriormente', grau: 3 },
  '01211': { denominacao: 'Horticultura', grau: 3 },
  '01229': { denominacao: 'Cultivo de flores e plantas ornamentais', grau: 3 },
  '01318': { denominacao: 'Cultivo de laranja', grau: 3 },
  '01326': { denominacao: 'Cultivo de uva', grau: 3 },
  '01334': { denominacao: 'Cultivo de frutas de lavoura permanente, exceto laranja e uva', grau: 3 },
  '01342': { denominacao: 'Cultivo de café', grau: 3 },
  '01351': { denominacao: 'Cultivo de cacau', grau: 3 },
  '01393': { denominacao: 'Cultivo de plantas de lavoura permanente não especificadas anteriormente', grau: 3 },
  '01415': { denominacao: 'Produção de sementes certificadas', grau: 3 },
  '01423': { denominacao: 'Produção de mudas e outras formas de propagação vegetal, certificadas', grau: 3 },
  '01512': { denominacao: 'Criação de bovinos', grau: 3 },
  '01521': { denominacao: 'Criação de outros animais de grande porte', grau: 3 },
  '01539': { denominacao: 'Criação de caprinos e ovinos', grau: 3 },
  '01547': { denominacao: 'Criação de suínos', grau: 3 },
  '01555': { denominacao: 'Criação de aves', grau: 3 },
  '01598': { denominacao: 'Criação de animais não especificados anteriormente', grau: 3 },
  '01610': { denominacao: 'Atividades de apoio à agricultura', grau: 3 },
  '01628': { denominacao: 'Atividades de apoio à pecuária', grau: 3 },
  '01636': { denominacao: 'Atividades de pós-colheita', grau: 3 },
  '01709': { denominacao: 'Caça e serviços relacionados', grau: 3 },
  '02101': { denominacao: 'Produção florestal - florestas plantadas', grau: 3 },
  '02209': { denominacao: 'Produção florestal - florestas nativas', grau: 4 },
  '02306': { denominacao: 'Atividades de apoio à produção florestal', grau: 3 },
  '03116': { denominacao: 'Pesca em água salgada', grau: 3 },
  '03124': { denominacao: 'Pesca em água doce', grau: 3 },
  '03213': { denominacao: 'Aquicultura em água salgada e salobra', grau: 3 },
  '03221': { denominacao: 'Aquicultura em água doce', grau: 3 },

  // ===== B — INDÚSTRIAS EXTRATIVAS =====
  '05003': { denominacao: 'Extração de carvão mineral', grau: 4 },
  '06000': { denominacao: 'Extração de petróleo e gás natural', grau: 4 },
  '07103': { denominacao: 'Extração de minério de ferro', grau: 4 },
  '07219': { denominacao: 'Extração de minério de alumínio', grau: 4 },
  '07227': { denominacao: 'Extração de minério de estanho', grau: 4 },
  '07235': { denominacao: 'Extração de minério de manganês', grau: 4 },
  '07243': { denominacao: 'Extração de minério de metais preciosos', grau: 4 },
  '07251': { denominacao: 'Extração de minerais radioativos', grau: 4 },
  '07294': { denominacao: 'Extração de minerais metálicos não-ferrosos não especificados anteriormente', grau: 4 },
  '08100': { denominacao: 'Extração de pedra, areia e argila', grau: 4 },
  '08916': { denominacao: 'Extração de minerais para fabricação de adubos, fertilizantes e outros produtos químicos', grau: 4 },
  '08924': { denominacao: 'Extração e refino de sal marinho e sal-gema', grau: 4 },
  '08932': { denominacao: 'Extração de gemas (pedras preciosas e semipreciosas)', grau: 4 },
  '08991': { denominacao: 'Extração de minerais não-metálicos não especificados anteriormente', grau: 4 },
  '09106': { denominacao: 'Atividades de apoio à extração de petróleo e gás natural', grau: 4 },
  '09904': { denominacao: 'Atividades de apoio à extração de minerais, exceto petróleo e gás natural', grau: 4 },

  // ===== C — INDÚSTRIAS DE TRANSFORMAÇÃO =====
  '10112': { denominacao: 'Abate de reses, exceto suínos', grau: 3 },
  '10121': { denominacao: 'Abate de suínos, aves e outros pequenos animais', grau: 3 },
  '10139': { denominacao: 'Fabricação de produtos de carne', grau: 3 },
  '10201': { denominacao: 'Preservação do pescado e fabricação de produtos do pescado', grau: 3 },
  '10317': { denominacao: 'Fabricação de conservas de frutas', grau: 3 },
  '10325': { denominacao: 'Fabricação de conservas de legumes e outros vegetais', grau: 3 },
  '10333': { denominacao: 'Fabricação de sucos de frutas, hortaliças e legumes', grau: 3 },
  '10414': { denominacao: 'Fabricação de óleos vegetais em bruto, exceto óleo de milho', grau: 3 },
  '10422': { denominacao: 'Fabricação de óleos vegetais refinados, exceto óleo de milho', grau: 3 },
  '10431': { denominacao: 'Fabricação de margarina e outras gorduras vegetais e de óleos não-comestíveis de animais', grau: 3 },
  '10511': { denominacao: 'Preparação do leite', grau: 3 },
  '10520': { denominacao: 'Fabricação de laticínios', grau: 3 },
  '10538': { denominacao: 'Fabricação de sorvetes e outros gelados comestíveis', grau: 3 },
  '10619': { denominacao: 'Beneficiamento de arroz e fabricação de produtos do arroz', grau: 3 },
  '10627': { denominacao: 'Moagem de trigo e fabricação de derivados', grau: 3 },
  '10635': { denominacao: 'Fabricação de farinha de mandioca e derivados', grau: 3 },
  '10643': { denominacao: 'Fabricação de farinha de milho e derivados, exceto óleos de milho', grau: 3 },
  '10651': { denominacao: 'Fabricação de amidos e féculas de vegetais e de óleos de milho', grau: 3 },
  '10660': { denominacao: 'Fabricação de alimentos para animais', grau: 3 },
  '10694': { denominacao: 'Moagem e fabricação de produtos de origem vegetal não especificados anteriormente', grau: 3 },
  '10716': { denominacao: 'Fabricação de açúcar em bruto', grau: 3 },
  '10724': { denominacao: 'Fabricação de açúcar refinado', grau: 3 },
  '10813': { denominacao: 'Torrefação e moagem de café', grau: 3 },
  '10821': { denominacao: 'Fabricação de produtos à base de café', grau: 3 },
  '10911': { denominacao: 'Fabricação de produtos de panificação', grau: 3 },
  '10929': { denominacao: 'Fabricação de biscoitos e bolachas', grau: 3 },
  '10937': { denominacao: 'Fabricação de produtos derivados do cacau, de chocolates e confeitos', grau: 3 },
  '10945': { denominacao: 'Fabricação de massas alimentícias', grau: 3 },
  '10953': { denominacao: 'Fabricação de especiarias, molhos, temperos e condimentos', grau: 3 },
  '10961': { denominacao: 'Fabricação de alimentos e pratos prontos', grau: 3 },
  '10996': { denominacao: 'Fabricação de produtos alimentícios não especificados anteriormente', grau: 3 },
  '11119': { denominacao: 'Fabricação de aguardentes e outras bebidas destiladas', grau: 3 },
  '11127': { denominacao: 'Fabricação de vinho', grau: 3 },
  '11135': { denominacao: 'Fabricação de malte, cervejas e chopes', grau: 3 },
  '11216': { denominacao: 'Fabricação de águas envasadas', grau: 3 },
  '11224': { denominacao: 'Fabricação de refrigerantes e de outras bebidas não-alcoólicas', grau: 3 },
  '12107': { denominacao: 'Processamento industrial do fumo', grau: 3 },
  '12204': { denominacao: 'Fabricação de produtos do fumo', grau: 3 },
  '13111': { denominacao: 'Preparação e fiação de fibras de algodão', grau: 3 },
  '13120': { denominacao: 'Preparação e fiação de fibras têxteis naturais, exceto algodão', grau: 3 },
  '13138': { denominacao: 'Fiação de fibras artificiais e sintéticas', grau: 3 },
  '13146': { denominacao: 'Fabricação de linhas para costurar e bordar', grau: 3 },
  '13219': { denominacao: 'Tecelagem de fios de algodão', grau: 3 },
  '13227': { denominacao: 'Tecelagem de fios de fibras têxteis naturais, exceto algodão', grau: 3 },
  '13235': { denominacao: 'Tecelagem de fios de fibras artificiais e sintéticas', grau: 3 },
  '13308': { denominacao: 'Fabricação de tecidos de malha', grau: 3 },
  '13405': { denominacao: 'Acabamentos em fios, tecidos e artefatos têxteis', grau: 3 },
  '13511': { denominacao: 'Fabricação de artefatos têxteis para uso doméstico', grau: 3 },
  '13529': { denominacao: 'Fabricação de artefatos de tapeçaria', grau: 3 },
  '13537': { denominacao: 'Fabricação de artefatos de cordoaria', grau: 3 },
  '13545': { denominacao: 'Fabricação de tecidos especiais, inclusive artefatos', grau: 3 },
  '13596': { denominacao: 'Fabricação de outros produtos têxteis não especificados anteriormente', grau: 3 },
  '14118': { denominacao: 'Confecção de roupas íntimas', grau: 2 },
  '14126': { denominacao: 'Confecção de peças do vestuário, exceto roupas íntimas', grau: 2 },
  '14134': { denominacao: 'Confecção de roupas profissionais', grau: 2 },
  '14142': { denominacao: 'Fabricação de acessórios do vestuário, exceto para segurança e proteção', grau: 2 },
  '14215': { denominacao: 'Fabricação de meias', grau: 2 },
  '14223': { denominacao: 'Fabricação de artigos do vestuário, produzidos em malharias e tricotagens, exceto meias', grau: 2 },
  '15106': { denominacao: 'Curtimento e outras preparações de couro', grau: 3 },
  '15211': { denominacao: 'Fabricação de artigos para viagem, bolsas e semelhantes de qualquer material', grau: 2 },
  '15297': { denominacao: 'Fabricação de artefatos de couro não especificados anteriormente', grau: 2 },
  '15319': { denominacao: 'Fabricação de calçados de couro', grau: 3 },
  '15327': { denominacao: 'Fabricação de tênis de qualquer material', grau: 3 },
  '15335': { denominacao: 'Fabricação de calçados de material sintético', grau: 3 },
  '15394': { denominacao: 'Fabricação de calçados de materiais não especificados anteriormente', grau: 3 },
  '15408': { denominacao: 'Fabricação de partes para calçados, de qualquer material', grau: 3 },
  '16102': { denominacao: 'Desdobramento de madeira', grau: 3 },
  '16218': { denominacao: 'Fabricação de madeira laminada e de chapas de madeira compensada, prensada e aglomerada', grau: 3 },
  '16226': { denominacao: 'Fabricação de estruturas de madeira e de artigos de carpintaria para construção', grau: 3 },
  '16234': { denominacao: 'Fabricação de artefatos de tanoaria e de embalagens de madeira', grau: 3 },
  '16293': { denominacao: 'Fabricação de artefatos de madeira, palha, cortiça, vime e material trançado não especificados anteriormente, exceto móveis', grau: 3 },
  '17109': { denominacao: 'Fabricação de celulose e outras pastas para a fabricação de papel', grau: 3 },
  '17214': { denominacao: 'Fabricação de papel', grau: 3 },
  '17222': { denominacao: 'Fabricação de cartolina e papel-cartão', grau: 3 },
  '17311': { denominacao: 'Fabricação de embalagens de papel', grau: 2 },
  '17320': { denominacao: 'Fabricação de embalagens de cartolina e papel-cartão', grau: 2 },
  '17338': { denominacao: 'Fabricação de chapas e de embalagens de papelão ondulado', grau: 2 },
  '17419': { denominacao: 'Fabricação de produtos de papel, cartolina, papel-cartão e papelão ondulado para uso comercial e de escritório', grau: 2 },
  '17427': { denominacao: 'Fabricação de produtos de papel para usos doméstico e higiênico-sanitário', grau: 2 },
  '17494': { denominacao: 'Fabricação de produtos de pastas celulósicas, papel, cartolina, papel-cartão e papelão ondulado não especificados anteriormente', grau: 2 },
  '18113': { denominacao: 'Impressão de jornais, livros, revistas e outras publicações periódicas', grau: 3 },
  '18121': { denominacao: 'Impressão de material de segurança', grau: 3 },
  '18130': { denominacao: 'Impressão de materiais para outros usos', grau: 3 },
  '18211': { denominacao: 'Serviços de pré-impressão', grau: 3 },
  '18229': { denominacao: 'Serviços de acabamentos gráficos', grau: 3 },
  '18300': { denominacao: 'Reprodução de materiais gravados em qualquer suporte', grau: 3 },
  '19101': { denominacao: 'Coquerias', grau: 3 },
  '19217': { denominacao: 'Fabricação de produtos do refino de petróleo', grau: 3 },
  '19225': { denominacao: 'Fabricação de produtos derivados do petróleo, exceto produtos do refino', grau: 3 },
  '19314': { denominacao: 'Fabricação de álcool', grau: 3 },
  '19322': { denominacao: 'Fabricação de biocombustíveis, exceto álcool', grau: 3 },
  '20118': { denominacao: 'Fabricação de cloro e álcalis', grau: 3 },
  '20126': { denominacao: 'Fabricação de intermediários para fertilizantes', grau: 3 },
  '20134': { denominacao: 'Fabricação de adubos e fertilizantes', grau: 3 },
  '20142': { denominacao: 'Fabricação de gases industriais', grau: 3 },
  '20193': { denominacao: 'Fabricação de produtos químicos inorgânicos não especificados anteriormente', grau: 3 },
  '20215': { denominacao: 'Fabricação de produtos petroquímicos básicos', grau: 3 },
  '20223': { denominacao: 'Fabricação de intermediários para plastificantes, resinas e fibras', grau: 3 },
  '20291': { denominacao: 'Fabricação de produtos químicos orgânicos não especificados anteriormente', grau: 3 },
  '20312': { denominacao: 'Fabricação de resinas termoplásticas', grau: 3 },
  '20321': { denominacao: 'Fabricação de resinas termofixas', grau: 3 },
  '20339': { denominacao: 'Fabricação de elastômeros', grau: 3 },
  '20401': { denominacao: 'Fabricação de fibras artificiais e sintéticas', grau: 3 },
  '20517': { denominacao: 'Fabricação de defensivos agrícolas', grau: 3 },
  '20525': { denominacao: 'Fabricação de desinfetantes domissanitários', grau: 3 },
  '20614': { denominacao: 'Fabricação de sabões e detergentes sintéticos', grau: 3 },
  '20622': { denominacao: 'Fabricação de produtos de limpeza e polimento', grau: 3 },
  '20631': { denominacao: 'Fabricação de cosméticos, produtos de perfumaria e de higiene pessoal', grau: 2 },
  '20711': { denominacao: 'Fabricação de tintas, vernizes, esmaltes e lacas', grau: 3 },
  '20720': { denominacao: 'Fabricação de tintas de impressão', grau: 3 },
  '20738': { denominacao: 'Fabricação de impermeabilizantes, solventes e produtos afins', grau: 3 },
  '20916': { denominacao: 'Fabricação de adesivos e selantes', grau: 3 },
  '20924': { denominacao: 'Fabricação de explosivos', grau: 4 },
  '20932': { denominacao: 'Fabricação de aditivos de uso industrial', grau: 3 },
  '20941': { denominacao: 'Fabricação de catalisadores', grau: 3 },
  '20991': { denominacao: 'Fabricação de produtos químicos não especificados anteriormente', grau: 3 },
  '21106': { denominacao: 'Fabricação de produtos farmoquímicos', grau: 3 },
  '21211': { denominacao: 'Fabricação de medicamentos para uso humano', grau: 3 },
  '21220': { denominacao: 'Fabricação de medicamentos para uso veterinário', grau: 3 },
  '21238': { denominacao: 'Fabricação de preparações farmacêuticas', grau: 3 },
  '22111': { denominacao: 'Fabricação de pneumáticos e de câmaras-de-ar', grau: 3 },
  '22129': { denominacao: 'Reforma de pneumáticos usados', grau: 3 },
  '22196': { denominacao: 'Fabricação de artefatos de borracha não especificados anteriormente', grau: 3 },
  '22218': { denominacao: 'Fabricação de laminados planos e tubulares de material plástico', grau: 3 },
  '22226': { denominacao: 'Fabricação de embalagens de material plástico', grau: 3 },
  '22234': { denominacao: 'Fabricação de tubos e acessórios de material plástico para uso na construção', grau: 3 },
  '22293': { denominacao: 'Fabricação de artefatos de material plástico não especificados anteriormente', grau: 3 },
  '23117': { denominacao: 'Fabricação de vidro plano e de segurança', grau: 3 },
  '23125': { denominacao: 'Fabricação de embalagens de vidro', grau: 3 },
  '23192': { denominacao: 'Fabricação de artigos de vidro', grau: 3 },
  '23206': { denominacao: 'Fabricação de cimento', grau: 4 },
  '23303': { denominacao: 'Fabricação de artefatos de concreto, cimento, fibrocimento, gesso e materiais semelhantes', grau: 4 },
  '23419': { denominacao: 'Fabricação de produtos cerâmicos refratários', grau: 4 },
  '23427': { denominacao: 'Fabricação de produtos cerâmicos não-refratários para uso estrutural na construção', grau: 3 },
  '23494': { denominacao: 'Fabricação de produtos cerâmicos não-refratários não especificados anteriormente', grau: 4 },
  '23915': { denominacao: 'Aparelhamento e outros trabalhos em pedras', grau: 3 },
  '23923': { denominacao: 'Fabricação de cal e gesso', grau: 4 },
  '23991': { denominacao: 'Fabricação de produtos de minerais não-metálicos não especificados anteriormente', grau: 3 },
  '24113': { denominacao: 'Produção de ferro-gusa', grau: 4 },
  '24121': { denominacao: 'Produção de ferroligas', grau: 4 },
  '24211': { denominacao: 'Produção de semi-acabados de aço', grau: 4 },
  '24229': { denominacao: 'Produção de laminados planos de aço', grau: 4 },
  '24237': { denominacao: 'Produção de laminados longos de aço', grau: 4 },
  '24245': { denominacao: 'Produção de relaminados, trefilados e perfilados de aço', grau: 4 },
  '24318': { denominacao: 'Produção de tubos de aço com costura', grau: 4 },
  '24393': { denominacao: 'Produção de outros tubos de ferro e aço', grau: 4 },
  '24415': { denominacao: 'Metalurgia do alumínio e suas ligas', grau: 4 },
  '24423': { denominacao: 'Metalurgia dos metais preciosos', grau: 4 },
  '24431': { denominacao: 'Metalurgia do cobre', grau: 4 },
  '24491': { denominacao: 'Metalurgia dos metais não-ferrosos e suas ligas não especificados anteriormente', grau: 4 },
  '24512': { denominacao: 'Fundição de ferro e aço', grau: 4 },
  '24521': { denominacao: 'Fundição de metais não-ferrosos e suas ligas', grau: 4 },
  '25110': { denominacao: 'Fabricação de estruturas metálicas', grau: 4 },
  '25128': { denominacao: 'Fabricação de esquadrias de metal', grau: 3 },
  '25136': { denominacao: 'Fabricação de obras de caldeiraria pesada', grau: 3 },
  '25217': { denominacao: 'Fabricação de tanques, reservatórios metálicos e caldeiras para aquecimento central', grau: 3 },
  '25225': { denominacao: 'Fabricação de caldeiras geradoras de vapor, exceto para aquecimento central e para veículos', grau: 3 },
  '25314': { denominacao: 'Produção de forjados de aço e de metais não-ferrosos e suas ligas', grau: 4 },
  '25322': { denominacao: 'Produção de artefatos estampados de metal; metalurgia do pó', grau: 4 },
  '25390': { denominacao: 'Serviços de usinagem, solda, tratamento e revestimento em metais', grau: 4 },
  '25411': { denominacao: 'Fabricação de artigos de cutelaria', grau: 3 },
  '25420': { denominacao: 'Fabricação de artigos de serralheria, exceto esquadrias', grau: 3 },
  '25438': { denominacao: 'Fabricação de ferramentas', grau: 3 },
  '25501': { denominacao: 'Fabricação de equipamento bélico pesado, armas de fogo e munições', grau: 4 },
  '25918': { denominacao: 'Fabricação de embalagens metálicas', grau: 3 },
  '25926': { denominacao: 'Fabricação de produtos de trefilados de metal', grau: 4 },
  '25934': { denominacao: 'Fabricação de artigos de metal para uso doméstico e pessoal', grau: 3 },
  '25993': { denominacao: 'Fabricação de produtos de metal não especificados anteriormente', grau: 3 },
  '26108': { denominacao: 'Fabricação de componentes eletrônicos', grau: 3 },
  '26213': { denominacao: 'Fabricação de equipamentos de informática', grau: 3 },
  '26221': { denominacao: 'Fabricação de periféricos para equipamentos de informática', grau: 3 },
  '26311': { denominacao: 'Fabricação de equipamentos transmissores de comunicação', grau: 3 },
  '26329': { denominacao: 'Fabricação de aparelhos telefônicos e de outros equipamentos de comunicação', grau: 3 },
  '26400': { denominacao: 'Fabricação de aparelhos de recepção, reprodução, gravação e amplificação de áudio e vídeo', grau: 3 },
  '26515': { denominacao: 'Fabricação de aparelhos e equipamentos de medida, teste e controle', grau: 3 },
  '26523': { denominacao: 'Fabricação de cronômetros e relógios', grau: 3 },
  '26604': { denominacao: 'Fabricação de aparelhos eletromédicos e eletroterapêuticos e equipamentos de irradiação', grau: 3 },
  '26701': { denominacao: 'Fabricação de equipamentos e instrumentos ópticos, fotográficos e cinematográficos', grau: 3 },
  '26809': { denominacao: 'Fabricação de mídias virgens, magnéticas e ópticas', grau: 3 },
  '27104': { denominacao: 'Fabricação de geradores, transformadores e motores elétricos', grau: 3 },
  '27210': { denominacao: 'Fabricação de pilhas, baterias e acumuladores elétricos, exceto para veículos automotores', grau: 3 },
  '27228': { denominacao: 'Fabricação de baterias e acumuladores para veículos automotores', grau: 3 },
  '27317': { denominacao: 'Fabricação de aparelhos e equipamentos para distribuição e controle de energia elétrica', grau: 3 },
  '27325': { denominacao: 'Fabricação de material elétrico para instalações em circuito de consumo', grau: 3 },
  '27333': { denominacao: 'Fabricação de fios, cabos e condutores elétricos isolados', grau: 3 },
  '27406': { denominacao: 'Fabricação de lâmpadas e outros equipamentos de iluminação', grau: 3 },
  '27511': { denominacao: 'Fabricação de fogões, refrigeradores e máquinas de lavar e secar para uso doméstico', grau: 3 },
  '27597': { denominacao: 'Fabricação de aparelhos eletrodomésticos não especificados anteriormente', grau: 3 },
  '27902': { denominacao: 'Fabricação de equipamentos e aparelhos elétricos não especificados anteriormente', grau: 3 },
  '28119': { denominacao: 'Fabricação de motores e turbinas, exceto para aviões e veículos rodoviários', grau: 3 },
  '28127': { denominacao: 'Fabricação de equipamentos hidráulicos e pneumáticos, exceto válvulas', grau: 3 },
  '28135': { denominacao: 'Fabricação de válvulas, registros e dispositivos semelhantes', grau: 3 },
  '28143': { denominacao: 'Fabricação de compressores', grau: 3 },
  '28151': { denominacao: 'Fabricação de equipamentos de transmissão para fins industriais', grau: 3 },
  '28216': { denominacao: 'Fabricação de aparelhos e equipamentos para instalações térmicas', grau: 3 },
  '28224': { denominacao: 'Fabricação de máquinas, equipamentos e aparelhos para transporte e elevação de cargas e pessoas', grau: 3 },
  '28232': { denominacao: 'Fabricação de máquinas e aparelhos de refrigeração e ventilação para uso industrial e comercial', grau: 3 },
  '28241': { denominacao: 'Fabricação de aparelhos e equipamentos de ar-condicionado', grau: 3 },
  '28259': { denominacao: 'Fabricação de máquinas e equipamentos para saneamento básico e ambiental', grau: 3 },
  '28291': { denominacao: 'Fabricação de máquinas e equipamentos de uso geral não especificados anteriormente', grau: 3 },
  '28313': { denominacao: 'Fabricação de tratores agrícolas', grau: 3 },
  '28321': { denominacao: 'Fabricação de equipamentos para irrigação agrícola', grau: 3 },
  '28330': { denominacao: 'Fabricação de máquinas e equipamentos para a agricultura e pecuária, exceto para irrigação', grau: 3 },
  '28402': { denominacao: 'Fabricação de máquinas-ferramenta', grau: 3 },
  '28518': { denominacao: 'Fabricação de máquinas e equipamentos para a prospecção e extração de petróleo', grau: 3 },
  '28526': { denominacao: 'Fabricação de outras máquinas e equipamentos para uso na extração mineral, exceto na extração de petróleo', grau: 3 },
  '28534': { denominacao: 'Fabricação de tratores, exceto agrícolas', grau: 3 },
  '28542': { denominacao: 'Fabricação de máquinas e equipamentos para terraplenagem, pavimentação e construção, exceto tratores', grau: 3 },
  '28615': { denominacao: 'Fabricação de máquinas para a indústria metalúrgica, exceto máquinas-ferramenta', grau: 3 },
  '28623': { denominacao: 'Fabricação de máquinas e equipamentos para as indústrias de alimentos, bebidas e fumo', grau: 3 },
  '28631': { denominacao: 'Fabricação de máquinas e equipamentos para a indústria têxtil', grau: 3 },
  '28640': { denominacao: 'Fabricação de máquinas e equipamentos para as indústrias do vestuário, do couro e de calçados', grau: 3 },
  '28658': { denominacao: 'Fabricação de máquinas e equipamentos para as indústrias de celulose, papel e papelão e artefatos', grau: 3 },
  '28666': { denominacao: 'Fabricação de máquinas e equipamentos para a indústria do plástico', grau: 3 },
  '28691': { denominacao: 'Fabricação de máquinas e equipamentos para uso industrial específico não especificados anteriormente', grau: 3 },
  '29107': { denominacao: 'Fabricação de automóveis, camionetas e utilitários', grau: 3 },
  '29204': { denominacao: 'Fabricação de caminhões e ônibus', grau: 3 },
  '29301': { denominacao: 'Fabricação de cabines, carrocerias e reboques para veículos automotores', grau: 3 },
  '29417': { denominacao: 'Fabricação de peças e acessórios para o sistema motor de veículos automotores', grau: 3 },
  '29425': { denominacao: 'Fabricação de peças e acessórios para os sistemas de marcha e transmissão de veículos automotores', grau: 3 },
  '29433': { denominacao: 'Fabricação de peças e acessórios para o sistema de freios de veículos automotores', grau: 3 },
  '29441': { denominacao: 'Fabricação de peças e acessórios para o sistema de direção e suspensão de veículos automotores', grau: 3 },
  '29450': { denominacao: 'Fabricação de material elétrico e eletrônico para veículos automotores, exceto baterias', grau: 3 },
  '29492': { denominacao: 'Fabricação de peças e acessórios para veículos automotores não especificados anteriormente', grau: 3 },
  '29506': { denominacao: 'Recondicionamento e recuperação de motores para veículos automotores', grau: 3 },
  '30113': { denominacao: 'Construção de embarcações e estruturas flutuantes', grau: 3 },
  '30121': { denominacao: 'Construção de embarcações para esporte e lazer', grau: 3 },
  '30318': { denominacao: 'Fabricação de locomotivas, vagões e outros materiais rodantes', grau: 3 },
  '30326': { denominacao: 'Fabricação de peças e acessórios para veículos ferroviários', grau: 3 },
  '30415': { denominacao: 'Fabricação de aeronaves', grau: 3 },
  '30423': { denominacao: 'Fabricação de turbinas, motores e outros componentes e peças para aeronaves', grau: 3 },
  '30504': { denominacao: 'Fabricação de veículos militares de combate', grau: 3 },
  '30911': { denominacao: 'Fabricação de motocicletas', grau: 3 },
  '30920': { denominacao: 'Fabricação de bicicletas e triciclos não-motorizados', grau: 3 },
  '30997': { denominacao: 'Fabricação de equipamentos de transporte não especificados anteriormente', grau: 3 },
  '31012': { denominacao: 'Fabricação de móveis com predominância de madeira', grau: 3 },
  '31021': { denominacao: 'Fabricação de móveis com predominância de metal', grau: 3 },
  '31039': { denominacao: 'Fabricação de móveis de outros materiais, exceto madeira e metal', grau: 3 },
  '31047': { denominacao: 'Fabricação de colchões', grau: 2 },
  '32116': { denominacao: 'Lapidação de gemas e fabricação de artefatos de ourivesaria e joalheria', grau: 3 },
  '32124': { denominacao: 'Fabricação de bijuterias e artefatos semelhantes', grau: 3 },
  '32205': { denominacao: 'Fabricação de instrumentos musicais', grau: 3 },
  '32302': { denominacao: 'Fabricação de artefatos para pesca e esporte', grau: 3 },
  '32400': { denominacao: 'Fabricação de brinquedos e jogos recreativos', grau: 3 },
  '32507': { denominacao: 'Fabricação de instrumentos e materiais para uso médico e odontológico e de artigos ópticos', grau: 3 },
  '32914': { denominacao: 'Fabricação de escovas, pincéis e vassouras', grau: 3 },
  '32922': { denominacao: 'Fabricação de equipamentos e acessórios para segurança e proteção pessoal e profissional', grau: 3 },
  '32990': { denominacao: 'Fabricação de produtos diversos não especificados anteriormente', grau: 3 },
  '33112': { denominacao: 'Manutenção e reparação de tanques, reservatórios metálicos e caldeiras, exceto para veículos', grau: 3 },
  '33121': { denominacao: 'Manutenção e reparação de equipamentos eletrônicos e ópticos', grau: 3 },
  '33139': { denominacao: 'Manutenção e reparação de máquinas e equipamentos elétricos', grau: 3 },
  '33147': { denominacao: 'Manutenção e reparação de máquinas e equipamentos da indústria mecânica', grau: 3 },
  '33155': { denominacao: 'Manutenção e reparação de veículos ferroviários', grau: 3 },
  '33163': { denominacao: 'Manutenção e reparação de aeronaves', grau: 3 },
  '33171': { denominacao: 'Manutenção e reparação de embarcações', grau: 3 },
  '33198': { denominacao: 'Manutenção e reparação de equipamentos e produtos não especificados anteriormente', grau: 3 },
  '33210': { denominacao: 'Instalação de máquinas e equipamentos industriais', grau: 3 },
  '33295': { denominacao: 'Instalação de equipamentos não especificados anteriormente', grau: 3 },

  // ===== D — ELETRICIDADE E GÁS =====
  '35115': { denominacao: 'Geração de energia elétrica', grau: 3 },
  '35123': { denominacao: 'Transmissão de energia elétrica', grau: 3 },
  '35131': { denominacao: 'Comércio atacadista de energia elétrica', grau: 3 },
  '35140': { denominacao: 'Distribuição de energia elétrica', grau: 3 },
  '35204': { denominacao: 'Produção de gás; processamento de gás natural; distribuição de combustíveis gasosos por redes urbanas', grau: 3 },
  '35301': { denominacao: 'Produção e distribuição de vapor, água quente e ar-condicionado', grau: 3 },

  // ===== E — ÁGUA, ESGOTO E GESTÃO DE RESÍDUOS =====
  '36006': { denominacao: 'Captação, tratamento e distribuição de água', grau: 3 },
  '37011': { denominacao: 'Gestão de redes de esgoto', grau: 3 },
  '37029': { denominacao: 'Atividades relacionadas a esgoto, exceto a gestão de redes', grau: 3 },
  '38114': { denominacao: 'Coleta de resíduos não-perigosos', grau: 3 },
  '38122': { denominacao: 'Coleta de resíduos perigosos', grau: 3 },
  '38211': { denominacao: 'Tratamento e disposição de resíduos não-perigosos', grau: 3 },
  '38220': { denominacao: 'Tratamento e disposição de resíduos perigosos', grau: 3 },
  '38319': { denominacao: 'Recuperação de materiais metálicos', grau: 3 },
  '38327': { denominacao: 'Recuperação de materiais plásticos', grau: 3 },
  '38394': { denominacao: 'Recuperação de materiais não especificados anteriormente', grau: 3 },
  '39005': { denominacao: 'Descontaminação e outros serviços de gestão de resíduos', grau: 3 },

  // ===== F — CONSTRUÇÃO =====
  '41107': { denominacao: 'Incorporação de empreendimentos imobiliários', grau: 1 },
  '41204': { denominacao: 'Construção de edifícios', grau: 3 },
  '42111': { denominacao: 'Construção de rodovias e ferrovias', grau: 4 },
  '42120': { denominacao: 'Construção de obras-de-arte especiais', grau: 4 },
  '42138': { denominacao: 'Obras de urbanização - ruas, praças e calçadas', grau: 3 },
  '42219': { denominacao: 'Obras para geração e distribuição de energia elétrica e para telecomunicações', grau: 4 },
  '42227': { denominacao: 'Construção de redes de abastecimento de água, coleta de esgoto e construções correlatas', grau: 4 },
  '42235': { denominacao: 'Construção de redes de transportes por dutos, exceto para água e esgoto', grau: 4 },
  '42910': { denominacao: 'Obras portuárias, marítimas e fluviais', grau: 4 },
  '42928': { denominacao: 'Montagem de instalações industriais e de estruturas metálicas', grau: 4 },
  '42995': { denominacao: 'Obras de engenharia civil não especificadas anteriormente', grau: 3 },
  '43118': { denominacao: 'Demolição e preparação de canteiros de obras', grau: 4 },
  '43126': { denominacao: 'Perfurações e sondagens', grau: 4 },
  '43134': { denominacao: 'Obras de terraplenagem', grau: 3 },
  '43193': { denominacao: 'Serviços de preparação do terreno não especificados anteriormente', grau: 3 },
  '43215': { denominacao: 'Instalações elétricas', grau: 3 },
  '43223': { denominacao: 'Instalações hidráulicas, de sistemas de ventilação e refrigeração', grau: 3 },
  '43291': { denominacao: 'Obras de instalações em construções não especificadas anteriormente', grau: 3 },
  '43304': { denominacao: 'Obras de acabamento', grau: 3 },
  '43916': { denominacao: 'Obras de fundações', grau: 4 },
  '43991': { denominacao: 'Serviços especializados para construção não especificados anteriormente', grau: 3 },

  // ===== G — COMÉRCIO; REPARAÇÃO DE VEÍCULOS =====
  '45111': { denominacao: 'Comércio a varejo e por atacado de veículos automotores', grau: 2 },
  '45129': { denominacao: 'Representantes comerciais e agentes do comércio de veículos automotores', grau: 2 },
  '45200': { denominacao: 'Manutenção e reparação de veículos automotores', grau: 3 },
  '45307': { denominacao: 'Comércio de peças e acessórios para veículos automotores', grau: 2 },
  '45412': { denominacao: 'Comércio por atacado e a varejo de motocicletas, peças e acessórios', grau: 2 },
  '45421': { denominacao: 'Representantes comerciais e agentes do comércio de motocicletas, peças e acessórios', grau: 2 },
  '45439': { denominacao: 'Manutenção e reparação de motocicletas', grau: 3 },
  '46117': { denominacao: 'Representantes comerciais e agentes do comércio de matérias-primas agrícolas e animais vivos', grau: 2 },
  '46125': { denominacao: 'Representantes comerciais e agentes do comércio de combustíveis, minerais, produtos siderúrgicos e químicos', grau: 2 },
  '46133': { denominacao: 'Representantes comerciais e agentes do comércio de madeira, material de construção e ferragens', grau: 2 },
  '46141': { denominacao: 'Representantes comerciais e agentes do comércio de máquinas, equipamentos, embarcações e aeronaves', grau: 2 },
  '46150': { denominacao: 'Representantes comerciais e agentes do comércio de eletrodomésticos, móveis e artigos de uso doméstico', grau: 2 },
  '46168': { denominacao: 'Representantes comerciais e agentes do comércio de têxteis, vestuário, calçados e artigos de viagem', grau: 2 },
  '46176': { denominacao: 'Representantes comerciais e agentes do comércio de produtos alimentícios, bebidas e fumo', grau: 2 },
  '46184': { denominacao: 'Representantes comerciais e agentes do comércio especializado em produtos não especificados anteriormente', grau: 2 },
  '46192': { denominacao: 'Representantes comerciais e agentes do comércio de mercadorias em geral não especializado', grau: 2 },
  '46214': { denominacao: 'Comércio atacadista de café em grão', grau: 2 },
  '46222': { denominacao: 'Comércio atacadista de soja', grau: 2 },
  '46231': { denominacao: 'Comércio atacadista de animais vivos, alimentos para animais e matérias-primas agrícolas, exceto café e soja', grau: 2 },
  '46311': { denominacao: 'Comércio atacadista de leite e laticínios', grau: 2 },
  '46320': { denominacao: 'Comércio atacadista de cereais e leguminosas beneficiados, farinhas, amidos e féculas', grau: 2 },
  '46338': { denominacao: 'Comércio atacadista de hortifrutigranjeiros', grau: 2 },
  '46346': { denominacao: 'Comércio atacadista de carnes, produtos da carne e pescado', grau: 2 },
  '46354': { denominacao: 'Comércio atacadista de bebidas', grau: 2 },
  '46362': { denominacao: 'Comércio atacadista de produtos do fumo', grau: 2 },
  '46371': { denominacao: 'Comércio atacadista especializado em produtos alimentícios não especificados anteriormente', grau: 2 },
  '46397': { denominacao: 'Comércio atacadista de produtos alimentícios em geral', grau: 2 },
  '46419': { denominacao: 'Comércio atacadista de tecidos, artefatos de tecidos e de armarinho', grau: 2 },
  '46427': { denominacao: 'Comércio atacadista de artigos do vestuário e acessórios', grau: 2 },
  '46435': { denominacao: 'Comércio atacadista de calçados e artigos de viagem', grau: 2 },
  '46443': { denominacao: 'Comércio atacadista de produtos farmacêuticos para uso humano e veterinário', grau: 2 },
  '46451': { denominacao: 'Comércio atacadista de instrumentos e materiais para uso médico, cirúrgico, ortopédico e odontológico', grau: 2 },
  '46460': { denominacao: 'Comércio atacadista de cosméticos, produtos de perfumaria e de higiene pessoal', grau: 2 },
  '46478': { denominacao: 'Comércio atacadista de artigos de escritório e de papelaria; livros, jornais e outras publicações', grau: 2 },
  '46494': { denominacao: 'Comércio atacadista de equipamentos e artigos de uso pessoal e doméstico não especificados anteriormente', grau: 2 },
  '46516': { denominacao: 'Comércio atacadista de computadores, periféricos e suprimentos de informática', grau: 3 },
  '46524': { denominacao: 'Comércio atacadista de componentes eletrônicos e equipamentos de telefonia e comunicação', grau: 3 },
  '46613': { denominacao: 'Comércio atacadista de máquinas, aparelhos e equipamentos para uso agropecuário; partes e peças', grau: 3 },
  '46621': { denominacao: 'Comércio atacadista de máquinas, equipamentos para terraplenagem, mineração e construção; partes e peças', grau: 3 },
  '46630': { denominacao: 'Comércio atacadista de máquinas e equipamentos para uso industrial; partes e peças', grau: 3 },
  '46648': { denominacao: 'Comércio atacadista de máquinas, aparelhos e equipamentos para uso odonto-médico-hospitalar; partes e peças', grau: 3 },
  '46656': { denominacao: 'Comércio atacadista de máquinas e equipamentos para uso comercial; partes e peças', grau: 3 },
  '46699': { denominacao: 'Comércio atacadista de máquinas, aparelhos e equipamentos não especificados anteriormente; partes e peças', grau: 3 },
  '46711': { denominacao: 'Comércio atacadista de madeira e produtos derivados', grau: 3 },
  '46729': { denominacao: 'Comércio atacadista de ferragens e ferramentas', grau: 3 },
  '46737': { denominacao: 'Comércio atacadista de material elétrico', grau: 3 },
  '46745': { denominacao: 'Comércio atacadista de cimento', grau: 3 },
  '46796': { denominacao: 'Comércio atacadista especializado de materiais de construção não especificados anteriormente e de materiais de construção em geral', grau: 3 },
  '46818': { denominacao: 'Comércio atacadista de combustíveis sólidos, líquidos e gasosos, exceto gás natural e GLP', grau: 3 },
  '46826': { denominacao: 'Comércio atacadista de gás liquefeito de petróleo (GLP)', grau: 3 },
  '46834': { denominacao: 'Comércio atacadista de defensivos agrícolas, adubos, fertilizantes e corretivos do solo', grau: 3 },
  '46842': { denominacao: 'Comércio atacadista de produtos químicos e petroquímicos, exceto agroquímicos', grau: 3 },
  '46851': { denominacao: 'Comércio atacadista de produtos siderúrgicos e metalúrgicos, exceto para construção', grau: 3 },
  '46869': { denominacao: 'Comércio atacadista de papel e papelão em bruto e de embalagens', grau: 3 },
  '46877': { denominacao: 'Comércio atacadista de resíduos e sucatas', grau: 3 },
  '46893': { denominacao: 'Comércio atacadista especializado de outros produtos intermediários não especificados anteriormente', grau: 3 },
  '46915': { denominacao: 'Comércio atacadista de mercadorias em geral, com predominância de produtos alimentícios', grau: 2 },
  '46923': { denominacao: 'Comércio atacadista de mercadorias em geral, com predominância de insumos agropecuários', grau: 2 },
  '46931': { denominacao: 'Comércio atacadista de mercadorias em geral, sem predominância de alimentos ou de insumos agropecuários', grau: 2 },
  '47113': { denominacao: 'Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - hipermercados e supermercados', grau: 2 },
  '47121': { denominacao: 'Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - minimercados, mercearias e armazéns', grau: 2 },
  '47130': { denominacao: 'Comércio varejista de mercadorias em geral, sem predominância de produtos alimentícios', grau: 2 },
  '47211': { denominacao: 'Comércio varejista de produtos de padaria, laticínio, doces, balas e semelhantes', grau: 2 },
  '47229': { denominacao: 'Comércio varejista de carnes e pescados - açougues e peixarias', grau: 3 },
  '47237': { denominacao: 'Comércio varejista de bebidas', grau: 2 },
  '47245': { denominacao: 'Comércio varejista de hortifrutigranjeiros', grau: 2 },
  '47296': { denominacao: 'Comércio varejista de produtos alimentícios em geral ou especializado em produtos alimentícios não especificados anteriormente; produtos do fumo', grau: 2 },
  '47318': { denominacao: 'Comércio varejista de combustíveis para veículos automotores', grau: 3 },
  '47326': { denominacao: 'Comércio varejista de lubrificantes', grau: 3 },
  '47415': { denominacao: 'Comércio varejista de tintas e materiais para pintura', grau: 2 },
  '47423': { denominacao: 'Comércio varejista de material elétrico', grau: 1 },
  '47431': { denominacao: 'Comércio varejista de vidros', grau: 2 },
  '47440': { denominacao: 'Comércio varejista de ferragens, madeira e materiais de construção', grau: 2 },
  '47512': { denominacao: 'Comércio varejista especializado de equipamentos e suprimentos de informática', grau: 1 },
  '47521': { denominacao: 'Comércio varejista especializado de equipamentos de telefonia e comunicação', grau: 1 },
  '47539': { denominacao: 'Comércio varejista especializado de eletrodomésticos e equipamentos de áudio e vídeo', grau: 1 },
  '47547': { denominacao: 'Comércio varejista especializado de móveis, colchoaria e artigos de iluminação', grau: 1 },
  '47555': { denominacao: 'Comércio varejista especializado de tecidos e artigos de cama, mesa e banho', grau: 1 },
  '47563': { denominacao: 'Comércio varejista especializado de instrumentos musicais e acessórios', grau: 1 },
  '47571': { denominacao: 'Comércio varejista especializado de peças e acessórios para aparelhos eletroeletrônicos para uso doméstico, exceto informática e comunicação', grau: 1 },
  '47598': { denominacao: 'Comércio varejista de artigos de uso doméstico não especificados anteriormente', grau: 1 },
  '47610': { denominacao: 'Comércio varejista de livros, jornais, revistas e papelaria', grau: 1 },
  '47628': { denominacao: 'Comércio varejista de discos, CDs, DVDs e fitas', grau: 1 },
  '47636': { denominacao: 'Comércio varejista de artigos recreativos e esportivos', grau: 1 },
  '47717': { denominacao: 'Comércio varejista de produtos farmacêuticos para uso humano e veterinário', grau: 2 },
  '47725': { denominacao: 'Comércio varejista de cosméticos, produtos de perfumaria e de higiene pessoal', grau: 1 },
  '47733': { denominacao: 'Comércio varejista de artigos médicos e ortopédicos', grau: 1 },
  '47741': { denominacao: 'Comércio varejista de artigos de óptica', grau: 1 },
  '47814': { denominacao: 'Comércio varejista de artigos do vestuário e acessórios', grau: 1 },
  '47822': { denominacao: 'Comércio varejista de calçados e artigos de viagem', grau: 1 },
  '47831': { denominacao: 'Comércio varejista de jóias e relógios', grau: 1 },
  '47849': { denominacao: 'Comércio varejista de gás liquefeito de petróleo (GLP)', grau: 3 },
  '47857': { denominacao: 'Comércio varejista de artigos usados', grau: 2 },
  '47890': { denominacao: 'Comércio varejista de outros produtos novos não especificados anteriormente', grau: 1 },
  '47903': { denominacao: 'Comércio ambulante e outros tipos de comércio varejista', grau: 2 },

  // ===== H — TRANSPORTE, ARMAZENAGEM E CORREIO =====
  '49116': { denominacao: 'Transporte ferroviário de carga', grau: 3 },
  '49124': { denominacao: 'Transporte metroferroviário de passageiros', grau: 3 },
  '49213': { denominacao: 'Transporte rodoviário coletivo de passageiros, com itinerário fixo, municipal e em região metropolitana', grau: 3 },
  '49221': { denominacao: 'Transporte rodoviário coletivo de passageiros, com itinerário fixo, intermunicipal, interestadual e internacional', grau: 3 },
  '49230': { denominacao: 'Transporte rodoviário de táxi', grau: 3 },
  '49248': { denominacao: 'Transporte escolar', grau: 3 },
  '49299': { denominacao: 'Transporte rodoviário coletivo de passageiros, sob regime de fretamento, e outros transportes rodoviários não especificados anteriormente', grau: 3 },
  '49302': { denominacao: 'Transporte rodoviário de carga', grau: 3 },
  '49400': { denominacao: 'Transporte dutoviário', grau: 3 },
  '49507': { denominacao: 'Trens turísticos, teleféricos e similares', grau: 3 },
  '50114': { denominacao: 'Transporte marítimo de cabotagem', grau: 3 },
  '50122': { denominacao: 'Transporte marítimo de longo curso', grau: 3 },
  '50211': { denominacao: 'Transporte por navegação interior de carga', grau: 3 },
  '50220': { denominacao: 'Transporte por navegação interior de passageiros em linhas regulares', grau: 3 },
  '50301': { denominacao: 'Navegação de apoio', grau: 3 },
  '50912': { denominacao: 'Transporte por navegação de travessia', grau: 3 },
  '50998': { denominacao: 'Transportes aquaviários não especificados anteriormente', grau: 3 },
  '51111': { denominacao: 'Transporte aéreo de passageiros regular', grau: 3 },
  '51129': { denominacao: 'Transporte aéreo de passageiros não-regular', grau: 3 },
  '51200': { denominacao: 'Transporte aéreo de carga', grau: 3 },
  '51307': { denominacao: 'Transporte espacial', grau: 3 },
  '52117': { denominacao: 'Armazenamento', grau: 3 },
  '52125': { denominacao: 'Carga e descarga', grau: 3 },
  '52214': { denominacao: 'Concessionárias de rodovias, pontes, túneis e serviços relacionados', grau: 3 },
  '52222': { denominacao: 'Terminais rodoviários e ferroviários', grau: 3 },
  '52231': { denominacao: 'Estacionamento de veículos', grau: 3 },
  '52290': { denominacao: 'Atividades auxiliares dos transportes terrestres não especificadas anteriormente', grau: 3 },
  '52311': { denominacao: 'Gestão de portos e terminais', grau: 3 },
  '52320': { denominacao: 'Atividades de agenciamento marítimo', grau: 3 },
  '52397': { denominacao: 'Atividades auxiliares dos transportes aquaviários não especificadas anteriormente', grau: 3 },
  '52401': { denominacao: 'Atividades auxiliares dos transportes aéreos', grau: 3 },
  '52508': { denominacao: 'Atividades relacionadas à organização do transporte de carga', grau: 3 },
  '53105': { denominacao: 'Atividades de Correio', grau: 2 },
  '53202': { denominacao: 'Atividades de malote e de entrega', grau: 2 },

  // ===== I — ALOJAMENTO E ALIMENTAÇÃO =====
  '55108': { denominacao: 'Hotéis e similares', grau: 2 },
  '55906': { denominacao: 'Outros tipos de alojamento não especificados anteriormente', grau: 2 },
  '56112': { denominacao: 'Restaurantes e outros estabelecimentos de serviços de alimentação e bebidas', grau: 2 },
  '56121': { denominacao: 'Serviços ambulantes de alimentação', grau: 2 },
  '56201': { denominacao: 'Serviços de catering, bufê e outros serviços de comida preparada', grau: 2 },

  // ===== J — INFORMAÇÃO E COMUNICAÇÃO =====
  '58115': { denominacao: 'Edição de livros', grau: 3 },
  '58123': { denominacao: 'Edição de jornais', grau: 3 },
  '58131': { denominacao: 'Edição de revistas', grau: 3 },
  '58191': { denominacao: 'Edição de cadastros, listas e outros produtos gráficos', grau: 3 },
  '58212': { denominacao: 'Edição integrada à impressão de livros', grau: 3 },
  '58221': { denominacao: 'Edição integrada à impressão de jornais', grau: 3 },
  '58239': { denominacao: 'Edição integrada à impressão de revistas', grau: 3 },
  '58298': { denominacao: 'Edição integrada à impressão de cadastros, listas e outros produtos gráficos', grau: 3 },
  '59111': { denominacao: 'Atividades de produção cinematográfica, de vídeos e de programas de televisão', grau: 2 },
  '59120': { denominacao: 'Atividades de pós-produção cinematográfica, de vídeos e de programas de televisão', grau: 2 },
  '59138': { denominacao: 'Distribuição cinematográfica, de vídeo e de programas de televisão', grau: 2 },
  '59146': { denominacao: 'Atividades de exibição cinematográfica', grau: 2 },
  '59201': { denominacao: 'Atividades de gravação de som e de edição de música', grau: 2 },
  '60101': { denominacao: 'Atividades de rádio', grau: 2 },
  '60217': { denominacao: 'Atividades de televisão aberta', grau: 2 },
  '60225': { denominacao: 'Programadoras e atividades relacionadas à televisão por assinatura', grau: 2 },
  '61108': { denominacao: 'Telecomunicações por fio', grau: 2 },
  '61205': { denominacao: 'Telecomunicações sem fio', grau: 2 },
  '61302': { denominacao: 'Telecomunicações por satélite', grau: 2 },
  '61418': { denominacao: 'Operadoras de televisão por assinatura por cabo', grau: 2 },
  '61426': { denominacao: 'Operadoras de televisão por assinatura por microondas', grau: 2 },
  '61434': { denominacao: 'Operadoras de televisão por assinatura por satélite', grau: 2 },
  '61906': { denominacao: 'Outras atividades de telecomunicações', grau: 2 },
  '62015': { denominacao: 'Desenvolvimento de programas de computador sob encomenda', grau: 2 },
  '62023': { denominacao: 'Desenvolvimento e licenciamento de programas de computador customizáveis', grau: 2 },
  '62031': { denominacao: 'Desenvolvimento e licenciamento de programas de computador não-customizáveis', grau: 2 },
  '62040': { denominacao: 'Consultoria em tecnologia da informação', grau: 2 },
  '62091': { denominacao: 'Suporte técnico, manutenção e outros serviços em tecnologia da informação', grau: 2 },
  '63119': { denominacao: 'Tratamento de dados, provedores de serviços de aplicação e serviços de hospedagem na internet', grau: 2 },
  '63194': { denominacao: 'Portais, provedores de conteúdo e outros serviços de informação na internet', grau: 2 },
  '63917': { denominacao: 'Agências de notícias', grau: 2 },
  '63992': { denominacao: 'Outras atividades de prestação de serviços de informação não especificadas anteriormente', grau: 2 },

  // ===== K — ATIVIDADES FINANCEIRAS E DE SEGUROS =====
  '64107': { denominacao: 'Banco Central', grau: 1 },
  '64212': { denominacao: 'Bancos comerciais', grau: 1 },
  '64221': { denominacao: 'Bancos múltiplos, com carteira comercial', grau: 1 },
  '64239': { denominacao: 'Caixas econômicas', grau: 1 },
  '64247': { denominacao: 'Crédito cooperativo', grau: 1 },
  '64310': { denominacao: 'Bancos múltiplos, sem carteira comercial', grau: 1 },
  '64328': { denominacao: 'Bancos de investimento', grau: 1 },
  '64336': { denominacao: 'Bancos de desenvolvimento', grau: 1 },
  '64344': { denominacao: 'Agências de fomento', grau: 1 },
  '64352': { denominacao: 'Crédito imobiliário', grau: 1 },
  '64361': { denominacao: 'Sociedades de crédito, financiamento e investimento - financeiras', grau: 1 },
  '64379': { denominacao: 'Sociedades de crédito ao microempreendedor', grau: 1 },
  '64387': { denominacao: 'Bancos de câmbio e outras instituições de intermediação não-monetária', grau: 1 },
  '64409': { denominacao: 'Arrendamento mercantil', grau: 1 },
  '64506': { denominacao: 'Sociedades de capitalização', grau: 1 },
  '64611': { denominacao: 'Holdings de instituições financeiras', grau: 1 },
  '64620': { denominacao: 'Holdings de instituições não-financeiras', grau: 1 },
  '64638': { denominacao: 'Outras sociedades de participação, exceto holdings', grau: 1 },
  '64701': { denominacao: 'Fundos de investimento', grau: 1 },
  '64913': { denominacao: 'Sociedades de fomento mercantil - factoring', grau: 1 },
  '64921': { denominacao: 'Securitização de créditos', grau: 1 },
  '64930': { denominacao: 'Administração de consórcios para aquisição de bens e direitos', grau: 1 },
  '64999': { denominacao: 'Outras atividades de serviços financeiros não especificadas anteriormente', grau: 1 },
  '65111': { denominacao: 'Seguros de vida', grau: 1 },
  '65120': { denominacao: 'Seguros não-vida', grau: 1 },
  '65201': { denominacao: 'Seguros-saúde', grau: 1 },
  '65308': { denominacao: 'Resseguros', grau: 1 },
  '65413': { denominacao: 'Previdência complementar fechada', grau: 1 },
  '65421': { denominacao: 'Previdência complementar aberta', grau: 1 },
  '65502': { denominacao: 'Planos de saúde', grau: 1 },
  '66118': { denominacao: 'Administração de bolsas e mercados de balcão organizados', grau: 1 },
  '66126': { denominacao: 'Atividades de intermediários em transações de títulos, valores mobiliários e mercadorias', grau: 1 },
  '66134': { denominacao: 'Administração de cartões de crédito', grau: 1 },
  '66193': { denominacao: 'Atividades auxiliares dos serviços financeiros não especificadas anteriormente', grau: 1 },
  '66215': { denominacao: 'Avaliação de riscos e perdas', grau: 1 },
  '66223': { denominacao: 'Corretores e agentes de seguros, de planos de previdência complementar e de saúde', grau: 1 },
  '66291': { denominacao: 'Atividades auxiliares dos seguros, da previdência complementar e dos planos de saúde não especificadas anteriormente', grau: 1 },
  '66304': { denominacao: 'Atividades de administração de fundos por contrato ou comissão', grau: 1 },

  // ===== L — ATIVIDADES IMOBILIÁRIAS =====
  '68102': { denominacao: 'Atividades imobiliárias de imóveis próprios', grau: 1 },
  '68218': { denominacao: 'Intermediação na compra, venda e aluguel de imóveis', grau: 1 },
  '68226': { denominacao: 'Gestão e administração da propriedade imobiliária', grau: 1 },

  // ===== M — ATIVIDADES PROFISSIONAIS, CIENTÍFICAS E TÉCNICAS =====
  '69117': { denominacao: 'Atividades jurídicas, exceto cartórios', grau: 1 },
  '69125': { denominacao: 'Cartórios', grau: 1 },
  '69206': { denominacao: 'Atividades de contabilidade, consultoria e auditoria contábil e tributária', grau: 1 },
  '70107': { denominacao: 'Sedes de empresas e unidades administrativas locais', grau: 1 },
  '70204': { denominacao: 'Atividades de consultoria em gestão empresarial', grau: 1 },
  '71111': { denominacao: 'Serviços de arquitetura', grau: 1 },
  '71120': { denominacao: 'Serviços de engenharia', grau: 1 },
  '71197': { denominacao: 'Atividades técnicas relacionadas à arquitetura e engenharia', grau: 1 },
  '71201': { denominacao: 'Testes e análises técnicas', grau: 2 },
  '72100': { denominacao: 'Pesquisa e desenvolvimento experimental em ciências físicas e naturais', grau: 2 },
  '72207': { denominacao: 'Pesquisa e desenvolvimento experimental em ciências sociais e humanas', grau: 2 },
  '73114': { denominacao: 'Agências de publicidade', grau: 1 },
  '73122': { denominacao: 'Agenciamento de espaços para publicidade, exceto em veículos de comunicação', grau: 1 },
  '73190': { denominacao: 'Atividades de publicidade não especificadas anteriormente', grau: 1 },
  '73203': { denominacao: 'Pesquisas de mercado e de opinião pública', grau: 1 },
  '74102': { denominacao: 'Design e decoração de interiores', grau: 1 },
  '74200': { denominacao: 'Atividades fotográficas e similares', grau: 2 },
  '74901': { denominacao: 'Atividades profissionais, científicas e técnicas não especificadas anteriormente', grau: 1 },
  '75001': { denominacao: 'Atividades veterinárias', grau: 3 },

  // ===== N — ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEMENTARES =====
  '77110': { denominacao: 'Locação de automóveis sem condutor', grau: 1 },
  '77195': { denominacao: 'Locação de meios de transporte, exceto automóveis, sem condutor', grau: 1 },
  '77217': { denominacao: 'Aluguel de equipamentos recreativos e esportivos', grau: 1 },
  '77225': { denominacao: 'Aluguel de fitas de vídeo, DVDs e similares', grau: 1 },
  '77233': { denominacao: 'Aluguel de objetos do vestuário, jóias e acessórios', grau: 1 },
  '77292': { denominacao: 'Aluguel de objetos pessoais e domésticos não especificados anteriormente', grau: 1 },
  '77314': { denominacao: 'Aluguel de máquinas e equipamentos agrícolas sem operador', grau: 1 },
  '77322': { denominacao: 'Aluguel de máquinas e equipamentos para construção sem operador', grau: 1 },
  '77331': { denominacao: 'Aluguel de máquinas e equipamentos para escritório', grau: 1 },
  '77390': { denominacao: 'Aluguel de máquinas e equipamentos não especificados anteriormente', grau: 1 },
  '77403': { denominacao: 'Gestão de ativos intangíveis não-financeiros', grau: 1 },
  '78108': { denominacao: 'Seleção e agenciamento de mão-de-obra', grau: 1 },
  '78205': { denominacao: 'Locação de mão-de-obra temporária', grau: 1 },
  '78302': { denominacao: 'Fornecimento e gestão de recursos humanos para terceiros', grau: 1 },
  '79112': { denominacao: 'Agências de viagens', grau: 1 },
  '79121': { denominacao: 'Operadores turísticos', grau: 1 },
  '79902': { denominacao: 'Serviços de reservas e outros serviços de turismo não especificados anteriormente', grau: 1 },
  '80111': { denominacao: 'Atividades de vigilância e segurança privada', grau: 3 },
  '80129': { denominacao: 'Atividades de transporte de valores', grau: 3 },
  '80200': { denominacao: 'Atividades de monitoramento de sistemas de segurança', grau: 3 },
  '80307': { denominacao: 'Atividades de investigação particular', grau: 3 },
  '81117': { denominacao: 'Serviços combinados para apoio a edifícios, exceto condomínios prediais', grau: 2 },
  '81125': { denominacao: 'Condomínios prediais', grau: 2 },
  '81214': { denominacao: 'Limpeza em prédios e em domicílios', grau: 3 },
  '81222': { denominacao: 'Imunização e controle de pragas urbanas', grau: 3 },
  '81290': { denominacao: 'Atividades de limpeza não especificadas anteriormente', grau: 3 },
  '81303': { denominacao: 'Atividades paisagísticas', grau: 1 },
  '82113': { denominacao: 'Serviços combinados de escritório e apoio administrativo', grau: 1 },
  '82199': { denominacao: 'Fotocópias, preparação de documentos e outros serviços especializados de apoio administrativo', grau: 2 },
  '82202': { denominacao: 'Atividades de teleatendimento', grau: 2 },
  '82300': { denominacao: 'Atividades de organização de eventos, exceto culturais e esportivos', grau: 2 },
  '82911': { denominacao: 'Atividades de cobrança e informações cadastrais', grau: 2 },
  '82920': { denominacao: 'Envasamento e empacotamento sob contrato', grau: 2 },
  '82997': { denominacao: 'Atividades de serviços prestados principalmente às empresas não especificadas anteriormente', grau: 2 },

  // ===== O — ADMINISTRAÇÃO PÚBLICA =====
  '84116': { denominacao: 'Administração pública em geral', grau: 1 },
  '84124': { denominacao: 'Regulação das atividades de saúde, educação, serviços culturais e outros serviços sociais', grau: 1 },
  '84132': { denominacao: 'Regulação das atividades econômicas', grau: 1 },
  '84213': { denominacao: 'Relações exteriores', grau: 1 },
  '84221': { denominacao: 'Defesa', grau: 1 },
  '84230': { denominacao: 'Justiça', grau: 1 },
  '84248': { denominacao: 'Segurança e ordem pública', grau: 1 },
  '84256': { denominacao: 'Defesa Civil', grau: 1 },
  '84302': { denominacao: 'Seguridade social obrigatória', grau: 1 },

  // ===== P — EDUCAÇÃO =====
  '85112': { denominacao: 'Educação infantil - creche', grau: 2 },
  '85121': { denominacao: 'Educação infantil - pré-escola', grau: 2 },
  '85139': { denominacao: 'Ensino fundamental', grau: 2 },
  '85201': { denominacao: 'Ensino médio', grau: 2 },
  '85317': { denominacao: 'Educação superior - graduação', grau: 2 },
  '85325': { denominacao: 'Educação superior - graduação e pós-graduação', grau: 2 },
  '85333': { denominacao: 'Educação superior - pós-graduação e extensão', grau: 2 },
  '85414': { denominacao: 'Educação profissional de nível técnico', grau: 2 },
  '85422': { denominacao: 'Educação profissional de nível tecnológico', grau: 2 },
  '85503': { denominacao: 'Atividades de apoio à educação', grau: 2 },
  '85911': { denominacao: 'Ensino de esportes', grau: 2 },
  '85929': { denominacao: 'Ensino de arte e cultura', grau: 2 },
  '85937': { denominacao: 'Ensino de idiomas', grau: 2 },
  '85996': { denominacao: 'Atividades de ensino não especificadas anteriormente', grau: 2 },

  // ===== Q — SAÚDE HUMANA E SERVIÇOS SOCIAIS =====
  '86101': { denominacao: 'Atividades de atendimento hospitalar', grau: 3 },
  '86216': { denominacao: 'Serviços móveis de atendimento a urgências', grau: 3 },
  '86224': { denominacao: 'Serviços de remoção de pacientes, exceto os serviços móveis de atendimento a urgências', grau: 3 },
  '86305': { denominacao: 'Atividades de atenção ambulatorial executadas por médicos e odontólogos', grau: 3 },
  '86402': { denominacao: 'Atividades de serviços de complementação diagnóstica e terapêutica', grau: 3 },
  '86500': { denominacao: 'Atividades de profissionais da área de saúde, exceto médicos e odontólogos', grau: 2 },
  '86607': { denominacao: 'Atividades de apoio à gestão de saúde', grau: 1 },
  '86909': { denominacao: 'Atividades de atenção à saúde humana não especificadas anteriormente', grau: 1 },
  '87115': { denominacao: 'Atividades de assistência a idosos, deficientes físicos, imunodeprimidos e convalescentes prestadas em residências coletivas e particulares', grau: 1 },
  '87123': { denominacao: 'Atividades de fornecimento de infra-estrutura de apoio e assistência a paciente no domicílio', grau: 1 },
  '87204': { denominacao: 'Atividades de assistência psicossocial e à saúde a portadores de distúrbios psíquicos, deficiência mental e dependência química', grau: 1 },
  '87301': { denominacao: 'Atividades de assistência social prestadas em residências coletivas e particulares', grau: 1 },
  '88006': { denominacao: 'Serviços de assistência social sem alojamento', grau: 1 },

  // ===== R — ARTES, CULTURA, ESPORTE E RECREAÇÃO =====
  '90019': { denominacao: 'Artes cênicas, espetáculos e atividades complementares', grau: 2 },
  '90027': { denominacao: 'Criação artística', grau: 2 },
  '90035': { denominacao: 'Gestão de espaços para artes cênicas, espetáculos e outras atividades artísticas', grau: 1 },
  '91015': { denominacao: 'Atividades de bibliotecas e arquivos', grau: 2 },
  '91023': { denominacao: 'Atividades de museus e de exploração, restauração artística e conservação de lugares e prédios históricos e atrações similares', grau: 2 },
  '91031': { denominacao: 'Atividades de jardins botânicos, zoológicos, parques nacionais, reservas ecológicas e áreas de proteção ambiental', grau: 2 },
  '92003': { denominacao: 'Atividades de exploração de jogos de azar e apostas', grau: 1 },
  '93115': { denominacao: 'Gestão de instalações de esportes', grau: 1 },
  '93123': { denominacao: 'Clubes sociais, esportivos e similares', grau: 2 },
  '93131': { denominacao: 'Atividades de condicionamento físico', grau: 2 },
  '93191': { denominacao: 'Atividades esportivas não especificadas anteriormente', grau: 2 },
  '93212': { denominacao: 'Parques de diversão e parques temáticos', grau: 2 },
  '93298': { denominacao: 'Atividades de recreação e lazer não especificadas anteriormente', grau: 2 },

  // ===== S — OUTRAS ATIVIDADES DE SERVIÇOS =====
  '94111': { denominacao: 'Atividades de organizações associativas patronais e empresariais', grau: 1 },
  '94120': { denominacao: 'Atividades de organizações associativas profissionais', grau: 1 },
  '94201': { denominacao: 'Atividades de organizações sindicais', grau: 1 },
  '94308': { denominacao: 'Atividades de associações de defesa de direitos sociais', grau: 1 },
  '94910': { denominacao: 'Atividades de organizações religiosas', grau: 1 },
  '94928': { denominacao: 'Atividades de organizações políticas', grau: 1 },
  '94936': { denominacao: 'Atividades de organizações associativas ligadas à cultura e à arte', grau: 1 },
  '94995': { denominacao: 'Atividades associativas não especificadas anteriormente', grau: 1 },
  '95118': { denominacao: 'Reparação e manutenção de computadores e de equipamentos periféricos', grau: 3 },
  '95126': { denominacao: 'Reparação e manutenção de equipamentos de comunicação', grau: 3 },
  '95215': { denominacao: 'Reparação e manutenção de equipamentos eletroeletrônicos de uso pessoal e doméstico', grau: 3 },
  '95291': { denominacao: 'Reparação e manutenção de objetos e equipamentos pessoais e domésticos não especificados anteriormente', grau: 3 },
  '96017': { denominacao: 'Lavanderias, tinturarias e toalheiros', grau: 2 },
  '96025': { denominacao: 'Cabeleireiros e outras atividades de tratamento de beleza', grau: 2 },
  '96033': { denominacao: 'Atividades funerárias e serviços relacionados', grau: 2 },
  '96092': { denominacao: 'Atividades de serviços pessoais não especificadas anteriormente', grau: 2 },

  // ===== T — SERVIÇOS DOMÉSTICOS =====
  '97005': { denominacao: 'Serviços domésticos', grau: 2 },

  // ===== U — ORGANISMOS INTERNACIONAIS =====
  '99008': { denominacao: 'Organismos internacionais e outras instituições extraterritoriais', grau: 1 },
};

/** Normaliza qualquer formato de CNAE para a classe de 5 dígitos. */
export function normalizarParaClasse(cnae: string): string | null {
  const digitos = (cnae || '').replace(/\D/g, '');
  if (digitos.length < 5) return null;
  return digitos.slice(0, 5);
}

export interface ConsultaGrauDeRisco {
  /** true apenas quando a classe consta no Anexo I. Nunca é estimado. */
  encontrado: boolean;
  classe: string | null;
  denominacao: string | null;
  grau: GrauDeRisco | null;
  fundamentacao: string;
}

/**
 * Consulta o grau de risco oficial.
 *
 * Retorna `encontrado: false` e `grau: null` quando a classe não consta no
 * Anexo I. NÃO estima, não usa a divisão como aproximação e não assume um
 * grau padrão: um grau errado aqui vira SESMT mal dimensionado e laudo com
 * enquadramento indevido. A decisão, nesse caso, é de quem tem habilitação.
 */
export function consultarGrauDeRisco(cnae: string): ConsultaGrauDeRisco {
  const classe = normalizarParaClasse(cnae);

  if (!classe) {
    return {
      encontrado: false,
      classe: null,
      denominacao: null,
      grau: null,
      fundamentacao: 'CNAE não informado ou incompleto. Informe ao menos os 5 dígitos da classe.',
    };
  }

  const item = NR4_ANEXO_I[classe];
  if (!item) {
    return {
      encontrado: false,
      classe,
      denominacao: null,
      grau: null,
      fundamentacao: `A classe CNAE ${formatarClasse(classe)} não consta no Anexo I da NR-04. Informe o grau de risco manualmente, com base na tabela oficial.`,
    };
  }

  return {
    encontrado: true,
    classe,
    denominacao: item.denominacao,
    grau: item.grau,
    fundamentacao: `Anexo I da NR-04 (Portaria MTP nº 2.318/2022, alterada pela Portaria MTP nº 4.219/2022) — classe ${formatarClasse(classe)}.`,
  };
}

/** Formata a classe de 5 dígitos como no Anexo I: 86500 -> 86.50-0 */
export function formatarClasse(classe: string): string {
  const d = classe.replace(/\D/g, '').padEnd(5, '0').slice(0, 5);
  return `${d.slice(0, 2)}.${d.slice(2, 4)}-${d.slice(4, 5)}`;
}

/** Busca por texto ou código, para os seletores de CNAE da interface. */
export function buscarClasses(consulta: string, limite = 30): Array<{ classe: string; codigo: string } & ClasseCnae> {
  const termo = (consulta || '').trim().toLowerCase();
  if (!termo) return [];

  const digitos = termo.replace(/\D/g, '');
  const semAcento = (t: string) => t.normalize('NFD').replace(/[̀-ͯ]/g, '');
  const alvo = semAcento(termo);

  const resultados: Array<{ classe: string; codigo: string } & ClasseCnae> = [];
  for (const [classe, item] of Object.entries(NR4_ANEXO_I)) {
    const casaCodigo = digitos.length >= 2 && classe.startsWith(digitos);
    const casaTexto = semAcento(item.denominacao.toLowerCase()).includes(alvo);
    if (casaCodigo || casaTexto) {
      resultados.push({ classe, codigo: formatarClasse(classe), ...item });
      if (resultados.length >= limite) break;
    }
  }
  return resultados;
}

/** Quantidade de classes na tabela — usado nos testes de integridade. */
export const TOTAL_CLASSES_ANEXO_I = Object.keys(NR4_ANEXO_I).length;
